/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hotelmanagementapp.views;

/**
 *
 * @author Santosh Lama
 * LMU ID: 23048594
 */
public class AdminDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashBoard
     */
    public AdminDashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainBody = new javax.swing.JPanel();
        lblTitleHotelLogo = new javax.swing.JLabel();
        pnlForTotalRooms = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlForTotalRevenue = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlForTotalCheckIns = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlForTotalCustomers = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTitleAdminDashBoard = new javax.swing.JLabel();
        btnGoBackToHomePage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMainBody.setBackground(new java.awt.Color(0, 31, 63));

        lblTitleHotelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hotelLogo.jpg"))); // NOI18N

        pnlForTotalRooms.setBackground(new java.awt.Color(58, 109, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Add a heading.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("7");

        javax.swing.GroupLayout pnlForTotalRoomsLayout = new javax.swing.GroupLayout(pnlForTotalRooms);
        pnlForTotalRooms.setLayout(pnlForTotalRoomsLayout);
        pnlForTotalRoomsLayout.setHorizontalGroup(
            pnlForTotalRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlForTotalRoomsLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlForTotalRoomsLayout.setVerticalGroup(
            pnlForTotalRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlForTotalRoomsLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlForTotalRevenue.setBackground(new java.awt.Color(0, 106, 103));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/revenueIcon.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rs 50,000");

        javax.swing.GroupLayout pnlForTotalRevenueLayout = new javax.swing.GroupLayout(pnlForTotalRevenue);
        pnlForTotalRevenue.setLayout(pnlForTotalRevenueLayout);
        pnlForTotalRevenueLayout.setHorizontalGroup(
            pnlForTotalRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlForTotalRevenueLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnlForTotalRevenueLayout.setVerticalGroup(
            pnlForTotalRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlForTotalRevenueLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlForTotalCheckIns.setBackground(new java.awt.Color(51, 0, 51));
        pnlForTotalCheckIns.setPreferredSize(new java.awt.Dimension(325, 256));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/totalCheckIns.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("80");

        javax.swing.GroupLayout pnlForTotalCheckInsLayout = new javax.swing.GroupLayout(pnlForTotalCheckIns);
        pnlForTotalCheckIns.setLayout(pnlForTotalCheckInsLayout);
        pnlForTotalCheckInsLayout.setHorizontalGroup(
            pnlForTotalCheckInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlForTotalCheckInsLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        pnlForTotalCheckInsLayout.setVerticalGroup(
            pnlForTotalCheckInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlForTotalCheckInsLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlForTotalCheckInsLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlForTotalCustomers.setBackground(new java.awt.Color(234, 216, 177));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/totalCustomers.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("25");

        javax.swing.GroupLayout pnlForTotalCustomersLayout = new javax.swing.GroupLayout(pnlForTotalCustomers);
        pnlForTotalCustomers.setLayout(pnlForTotalCustomersLayout);
        pnlForTotalCustomersLayout.setHorizontalGroup(
            pnlForTotalCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlForTotalCustomersLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(0, 58, Short.MAX_VALUE))
        );
        pnlForTotalCustomersLayout.setVerticalGroup(
            pnlForTotalCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlForTotalCustomersLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitleAdminDashBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/adminDashBoard.png"))); // NOI18N

        btnGoBackToHomePage.setBackground(new java.awt.Color(153, 0, 0));
        btnGoBackToHomePage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGoBackToHomePage.setForeground(new java.awt.Color(204, 204, 204));
        btnGoBackToHomePage.setText("Back to Home");
        btnGoBackToHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackToHomePageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainBodyLayout = new javax.swing.GroupLayout(pnlMainBody);
        pnlMainBody.setLayout(pnlMainBodyLayout);
        pnlMainBodyLayout.setHorizontalGroup(
            pnlMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitleHotelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
            .addGroup(pnlMainBodyLayout.createSequentialGroup()
                .addGroup(pnlMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainBodyLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(lblTitleAdminDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainBodyLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(pnlMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlForTotalRooms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlForTotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlForTotalCheckIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlForTotalCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainBodyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGoBackToHomePage)
                .addGap(438, 438, 438))
        );
        pnlMainBodyLayout.setVerticalGroup(
            pnlMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainBodyLayout.createSequentialGroup()
                .addComponent(lblTitleHotelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblTitleAdminDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlForTotalRooms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlForTotalCheckIns, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlForTotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlForTotalCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGoBackToHomePage)
                .addContainerGap())
        );

        getContentPane().add(pnlMainBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Handles the action event when the "Go Back to Home Page" button is
     * clicked. This method creates an instance of the HomePage class and
     * displays it, effectively navigating the user back to the home page. The
     * current window is disposed of to free resources and prevent multiple
     * instances.
     *
     * @param evt the ActionEvent triggered by clicking the button
     */
    private void btnGoBackToHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackToHomePageActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnGoBackToHomePageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBackToHomePage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTitleAdminDashBoard;
    private javax.swing.JLabel lblTitleHotelLogo;
    private javax.swing.JPanel pnlForTotalCheckIns;
    private javax.swing.JPanel pnlForTotalCustomers;
    private javax.swing.JPanel pnlForTotalRevenue;
    private javax.swing.JPanel pnlForTotalRooms;
    private javax.swing.JPanel pnlMainBody;
    // End of variables declaration//GEN-END:variables
}
