/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hotelmanagementapp.views;

import com.hotelmanagementapp.util.ValidationUtil;
import javax.swing.JOptionPane;

/**
 *
 * @author 23048594 Santosh Lama
 */
public class CustomerCheckOut extends javax.swing.JFrame {

    /**
     * Creates new form demo
     */
    public CustomerCheckOut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageCheckOutBackground = new javax.swing.JLabel();
        lblTitleHotelLogo = new javax.swing.JLabel();
        pnlBodyMain = new javax.swing.JPanel();
        pnlForm = new javax.swing.JPanel();
        lblRoomNumber = new javax.swing.JLabel();
        txtFieldRoomNumber = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnCheckOutNow = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnViewTable = new javax.swing.JButton();
        txtFieldCustomerName = new javax.swing.JTextField();
        txtFieldMobileNumber = new javax.swing.JTextField();
        txtFieldTotalAmount = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        txtFieldPricePerDay = new javax.swing.JTextField();
        txtFieldCheckOutDate = new javax.swing.JTextField();
        lblCustomerName = new javax.swing.JLabel();
        lblMobileNumber = new javax.swing.JLabel();
        lblCheckInDate = new javax.swing.JLabel();
        lblCheckOutDate = new javax.swing.JLabel();
        lblPricePerDay = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        btnBackToHomePage = new javax.swing.JButton();
        pnlTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblManageCheckOutBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MANAGE CHECK-OUTs.jpg"))); // NOI18N
        getContentPane().add(lblManageCheckOutBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1000, 200));

        lblTitleHotelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hotelLogo.jpg"))); // NOI18N
        getContentPane().add(lblTitleHotelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 91));

        pnlBodyMain.setLayout(new java.awt.CardLayout());

        pnlForm.setBackground(new java.awt.Color(234, 216, 177));

        lblRoomNumber.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblRoomNumber.setForeground(new java.awt.Color(102, 102, 102));
        lblRoomNumber.setText("Room Number");

        btnSearch.setBackground(new java.awt.Color(153, 0, 0));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");

        btnCheckOutNow.setBackground(new java.awt.Color(58, 109, 140));
        btnCheckOutNow.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCheckOutNow.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckOutNow.setText("Check Out Now");
        btnCheckOutNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutNowActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(153, 0, 0));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");

        btnViewTable.setBackground(new java.awt.Color(58, 109, 140));
        btnViewTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewTable.setForeground(new java.awt.Color(255, 255, 255));
        btnViewTable.setText("View Table");
        btnViewTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTableActionPerformed(evt);
            }
        });

        lblCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(102, 102, 102));
        lblCustomerName.setText("Customer Name");

        lblMobileNumber.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblMobileNumber.setForeground(new java.awt.Color(102, 102, 102));
        lblMobileNumber.setText("Mobile Number");

        lblCheckInDate.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCheckInDate.setForeground(new java.awt.Color(102, 102, 102));
        lblCheckInDate.setText("Check-In Date");

        lblCheckOutDate.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCheckOutDate.setForeground(new java.awt.Color(102, 102, 102));
        lblCheckOutDate.setText("Check-Out Date");

        lblPricePerDay.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblPricePerDay.setForeground(new java.awt.Color(102, 102, 102));
        lblPricePerDay.setText("Price Per Day");

        lblTotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblTotalAmount.setForeground(new java.awt.Color(102, 102, 102));
        lblTotalAmount.setText("Total Amount");

        btnBackToHomePage.setBackground(new java.awt.Color(58, 109, 140));
        btnBackToHomePage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBackToHomePage.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToHomePage.setText("Back To Home Page");
        btnBackToHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomePageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRoomNumber)
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addComponent(txtFieldRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnSearch))))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlFormLayout.createSequentialGroup()
                                        .addComponent(txtFieldCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(167, 167, 167))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                                        .addComponent(btnCheckOutNow)
                                        .addGap(47, 47, 47)
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)))
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMobileNumber)
                                    .addGroup(pnlFormLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(btnViewTable))))
                            .addComponent(lblCustomerName)
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(167, 167, 167)
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldCheckOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCheckOutDate)))
                            .addComponent(lblCheckInDate)
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addComponent(txtFieldPricePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(167, 167, 167)
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTotalAmount)))
                            .addComponent(lblPricePerDay)))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(btnBackToHomePage)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblRoomNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(11, 11, 11)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerName)
                    .addComponent(lblMobileNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCheckInDate)
                    .addComponent(lblCheckOutDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldCheckOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPricePerDay)
                    .addComponent(lblTotalAmount))
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldPricePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCheckOutNow, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewTable, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBackToHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(614, Short.MAX_VALUE))
        );

        pnlBodyMain.add(pnlForm, "card2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Customer Name", "Mobile Number", "Room Number", "Check In Date", "Bill ID", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jButton1.setBackground(new java.awt.Color(153, 51, 0));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Switch Panel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(683, Short.MAX_VALUE))
        );

        pnlBodyMain.add(pnlTable, "card3");

        getContentPane().add(pnlBodyMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 296, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTableActionPerformed
        // TODO add your handling code here:
        pnlTable.setVisible(true);
        pnlForm.setVisible(false);
    }//GEN-LAST:event_btnViewTableActionPerformed

    private void btnBackToHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomePageActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackToHomePageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pnlForm.setVisible(true);
        pnlTable.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCheckOutNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutNowActionPerformed
        // TODO add your handling code here:
        // Retrieve input values
        String roomNumber = txtFieldRoomNumber.getText().trim();
        String customerName = txtFieldCustomerName.getText().trim();
        String mobileNumber = txtFieldMobileNumber.getText().trim();
        String pricePerDay = txtFieldPricePerDay.getText().trim();
        String totalAmount = txtFieldTotalAmount.getText().trim();

        //Validate Room Number
        if (roomNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Room Number is required. Please enter a valid room number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            txtFieldRoomNumber.requestFocus();
        } else if (!ValidationUtil.isValidRoomNumber(roomNumber)) {
            JOptionPane.showMessageDialog(this, "Invalid Room Number. It must be a numeric value (1-5 digits) and cannot start with a zero.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            txtFieldRoomNumber.requestFocus();
        } // Validate Customer Name
        else if (customerName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Customer Name is required. Please enter a valid name.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            txtFieldCustomerName.requestFocus();
        } else if (!ValidationUtil.isValidCustomerName(customerName)) {
            JOptionPane.showMessageDialog(this, "Invalid Customer Name. It must contain 2-50 alphabetic characters.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            txtFieldCustomerName.requestFocus();
        } // Validate Mobile Number
        else if (mobileNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mobile Number is required. Please enter a valid mobile number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            txtFieldMobileNumber.requestFocus();
        } else if (!ValidationUtil.isValidMobileNumber(mobileNumber)) {
            JOptionPane.showMessageDialog(this, "Invalid Mobile Number. It must be a 10-digit number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            txtFieldMobileNumber.requestFocus();
        } else if (pricePerDay.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Amount  is required. Please enter the amount.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            txtFieldPricePerDay.requestFocus();
        } else if (!ValidationUtil.isValidPrice(pricePerDay)) {
            JOptionPane.showMessageDialog(this, "Invalid amount. It must be a positive number with optional decimal points (up to 2 decimal places).", "Validation Error", JOptionPane.ERROR_MESSAGE);
            txtFieldPricePerDay.requestFocus();
        } else if (totalAmount.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Amount  is required. Please enter the amount.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            txtFieldTotalAmount.requestFocus();
        } else if (!ValidationUtil.isValidPrice(totalAmount)) {
            JOptionPane.showMessageDialog(this, "Invalid amount. It must be a positive number with optional decimal points (up to 2 decimal places).", "Validation Error", JOptionPane.ERROR_MESSAGE);
            txtFieldTotalAmount.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Check-Out Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCheckOutNowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToHomePage;
    private javax.swing.JButton btnCheckOutNow;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblCheckInDate;
    private javax.swing.JLabel lblCheckOutDate;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblManageCheckOutBackground;
    private javax.swing.JLabel lblMobileNumber;
    private javax.swing.JLabel lblPricePerDay;
    private javax.swing.JLabel lblRoomNumber;
    private javax.swing.JLabel lblTitleHotelLogo;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JPanel pnlBodyMain;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JTextField txtFieldCheckOutDate;
    private javax.swing.JTextField txtFieldCustomerName;
    private javax.swing.JTextField txtFieldMobileNumber;
    private javax.swing.JTextField txtFieldPricePerDay;
    private javax.swing.JTextField txtFieldRoomNumber;
    private javax.swing.JTextField txtFieldTotalAmount;
    // End of variables declaration//GEN-END:variables
}
