/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hotelmanagementapp.views;

import javax.swing.JOptionPane;

/**
 *
 * @author lamab
 */

public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form homePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeroSection = new javax.swing.JPanel();
        lblHomePageBackgroundImage = new javax.swing.JLabel();
        menuBarMain = new javax.swing.JMenuBar();
        menuManageRooms = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuCustomerCheckIn = new javax.swing.JMenu();
        menuCustomerCheckOut = new javax.swing.JMenu();
        menuDashBoard = new javax.swing.JMenu();
        menuBill = new javax.swing.JMenu();
        menuLogOut = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 10));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHomePageBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hotelHomePageBackground.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlHeroSectionLayout = new javax.swing.GroupLayout(pnlHeroSection);
        pnlHeroSection.setLayout(pnlHeroSectionLayout);
        pnlHeroSectionLayout.setHorizontalGroup(
            pnlHeroSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHomePageBackgroundImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHeroSectionLayout.setVerticalGroup(
            pnlHeroSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeroSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHomePageBackgroundImage, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlHeroSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 22, -1, -1));

        menuBarMain.setBackground(new java.awt.Color(102, 102, 102));

        menuManageRooms.setBackground(new java.awt.Color(153, 153, 153));
        menuManageRooms.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuManageRooms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/manageRoomIcon.png"))); // NOI18N
        menuManageRooms.setText("Manage Rooms");
        menuManageRooms.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        menuManageRooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuManageRoomsMouseClicked(evt);
            }
        });
        menuManageRooms.add(jSeparator1);

        menuBarMain.add(menuManageRooms);

        menuCustomerCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/checkInIcon.png"))); // NOI18N
        menuCustomerCheckIn.setText("Customer Check-In");
        menuCustomerCheckIn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        menuCustomerCheckIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCustomerCheckInMouseClicked(evt);
            }
        });
        menuBarMain.add(menuCustomerCheckIn);

        menuCustomerCheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/checkOutIcon.png"))); // NOI18N
        menuCustomerCheckOut.setText("Customer Check-Out");
        menuCustomerCheckOut.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        menuCustomerCheckOut.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuCustomerCheckOutMenuSelected(evt);
            }
        });
        menuBarMain.add(menuCustomerCheckOut);

        menuDashBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dashBoardIcon.png"))); // NOI18N
        menuDashBoard.setText("DashBoard");
        menuDashBoard.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        menuDashBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDashBoardMouseClicked(evt);
            }
        });
        menuBarMain.add(menuDashBoard);

        menuBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/billIcon.png"))); // NOI18N
        menuBill.setText("Bill");
        menuBill.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        menuBarMain.add(menuBill);

        menuLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logoutIcon.png"))); // NOI18N
        menuLogOut.setText("Log Out");
        menuLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        menuLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogOutMouseClicked(evt);
            }
        });
        menuBarMain.add(menuLogOut);

        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/close (1).png"))); // NOI18N
        menuExit.setText("Exit");
        menuExit.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        menuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuExitMouseClicked(evt);
            }
        });
        menuBarMain.add(menuExit);

        setJMenuBar(menuBarMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuManageRoomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuManageRoomsMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ManageRooms().setVisible(true);
    }//GEN-LAST:event_menuManageRoomsMouseClicked

    private void menuCustomerCheckInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCustomerCheckInMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new CustomerCheckIn().setVisible(true);
    }//GEN-LAST:event_menuCustomerCheckInMouseClicked

    private void menuCustomerCheckOutMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuCustomerCheckOutMenuSelected
        // TODO add your handling code here:
        this.setVisible(false);
        new CustomerCheckOut().setVisible(true);
    }//GEN-LAST:event_menuCustomerCheckOutMenuSelected

    private void menuLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogOutMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to log out?",
                "Confirm Logout",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        // Handle the user's response
        if (response == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new LoginPage().setVisible(true);
        } else {
            // If the user selects "No," do nothing
            System.out.println("Logout canceled by user.");
        }
    }//GEN-LAST:event_menuLogOutMouseClicked

    private void menuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExitMouseClicked

        int response = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to exit?",
                "Exit Confirmation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (response == JOptionPane.YES_OPTION) {
            // Close the application
            System.exit(0);
        } else {
            // Log or handle if the user chooses not to exit
            System.out.println("User canceled the exit operation.");
        }
  

    }//GEN-LAST:event_menuExitMouseClicked

    private void menuDashBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashBoardMouseClicked
        // TODO add your handling code here:
        new AdminDashBoard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuDashBoardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new HomePage().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblHomePageBackgroundImage;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuBill;
    private javax.swing.JMenu menuCustomerCheckIn;
    private javax.swing.JMenu menuCustomerCheckOut;
    private javax.swing.JMenu menuDashBoard;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenu menuLogOut;
    private javax.swing.JMenu menuManageRooms;
    private javax.swing.JPanel pnlHeroSection;
    // End of variables declaration//GEN-END:variables
}
