/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hotelmanagementapp.views;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 23048594 
 * Santosh Lama
 */
/**
 * LoadingPage class simulates the loading process of the Hotel Management
 * System with a progress bar and status updates. Once the loading completes, it
 * transitions to the LoginPage and disposes of the LoadingPage.
 *
 */
public class LoadingPage extends javax.swing.JFrame {

    /**
     * Creates new form loadingFrame
     */
    public LoadingPage() {
        initComponents();
        startLoadingProcess(); // method call inside the constructor for dynamic flow of progress bar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlLoginForm1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblHotelLogo = new javax.swing.JLabel();
        lblWelcomeTitle = new javax.swing.JLabel();
        loadingProgressBar = new javax.swing.JProgressBar();
        lblLoadingTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain.setBackground(new java.awt.Color(0, 31, 63));

        pnlLoginForm1.setPreferredSize(new java.awt.Dimension(599, 481));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hotelBackgroundForLoadingScreen.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlLoginForm1Layout = new javax.swing.GroupLayout(pnlLoginForm1);
        pnlLoginForm1.setLayout(pnlLoginForm1Layout);
        pnlLoginForm1Layout.setHorizontalGroup(
            pnlLoginForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlLoginForm1Layout.setVerticalGroup(
            pnlLoginForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblHotelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hotelLogo.jpg"))); // NOI18N

        lblWelcomeTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWelcomeTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeTitle.setText("WELCOME TO HOTEL MANAGEMENT SYSTEM");

        loadingProgressBar.setStringPainted(true);

        lblLoadingTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLoadingTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblLoadingTitle.setText("Loading....");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHotelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(pnlLoginForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(lblWelcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addComponent(loadingProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addComponent(lblLoadingTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(lblHotelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(pnlLoginForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWelcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblLoadingTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loadingProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Simulates a loading process with a progress bar and status updates.
     *
     * Updates progress and status messages at milestones. Transitions to the
     * main application screen upon completion.
     */
    private void startLoadingProcess() {
        Thread loadingPercentage = new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i <= 100; i++) {
                    loadingProgressBar.setValue(i);
                    try {
                        Thread.sleep(50); // Adjust delay as needed
                    } catch (InterruptedException ex) {
                        Logger.getLogger(LoadingPage.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    // Update the loading title based on progress
                    if (i == 10) {
                        lblLoadingTitle.setText("Starting up application...");
                    } else if (i == 25) {
                        lblLoadingTitle.setText("Loading resources...");
                    } else if (i == 50) {
                        lblLoadingTitle.setText("Initializing components...");
                    } else if (i == 75) {
                        lblLoadingTitle.setText("Finalizing setup...");
                    } else if (i == 100) {
                        lblLoadingTitle.setText("Application loaded successfully!");
                        new LoginPage().setVisible(true);
                        LoadingPage.this.dispose();
                    }
                }
            }
        });

        // Start the thread
        loadingPercentage.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblHotelLogo;
    private javax.swing.JLabel lblLoadingTitle;
    private javax.swing.JLabel lblWelcomeTitle;
    private javax.swing.JProgressBar loadingProgressBar;
    private javax.swing.JPanel pnlLoginForm1;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
