/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hotelmanagementapp.views;

import javax.swing.JOptionPane;

/**
 *
 * @author 23048594 Santosh Lama
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form HotelApp
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLoginFrame1 = new javax.swing.JPanel();
        pnlLoginForm1 = new javax.swing.JPanel();
        lblLoginWelcomeTitle1 = new javax.swing.JLabel();
        txtFieldEmailAddress1 = new javax.swing.JTextField();
        btnLogin1 = new javax.swing.JButton();
        btnSignUp1 = new javax.swing.JButton();
        lblSubTitleForLoginInstructions1 = new javax.swing.JLabel();
        pwdFieldForLogin = new javax.swing.JPasswordField();
        lblLoginBackground = new javax.swing.JLabel();
        btnShow = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLoginFrame1.setBackground(new java.awt.Color(0, 31, 63));

        lblLoginWelcomeTitle1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLoginWelcomeTitle1.setForeground(new java.awt.Color(27, 35, 86));
        lblLoginWelcomeTitle1.setText("Welcome back, Admin!");

        txtFieldEmailAddress1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N

        btnLogin1.setBackground(new java.awt.Color(27, 35, 86));
        btnLogin1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin1.setText("LOGIN");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        btnSignUp1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSignUp1.setText("SIGN UP");
        btnSignUp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSubTitleForLoginInstructions1.setForeground(new java.awt.Color(153, 153, 153));
        lblSubTitleForLoginInstructions1.setText("Please login to your account by filling in the details");

        pwdFieldForLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pwdFieldForLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdFieldForLoginActionPerformed(evt);
            }
        });

        lblLoginBackground.setBackground(new java.awt.Color(0, 31, 63));
        lblLoginBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/loginBackground.png"))); // NOI18N

        btnShow.setBackground(new java.awt.Color(27, 35, 86));
        btnShow.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnShow.setForeground(new java.awt.Color(255, 255, 255));
        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        lblErrorMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlLoginForm1Layout = new javax.swing.GroupLayout(pnlLoginForm1);
        pnlLoginForm1.setLayout(pnlLoginForm1Layout);
        pnlLoginForm1Layout.setHorizontalGroup(
            pnlLoginForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginForm1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlLoginForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSubTitleForLoginInstructions1)
                    .addComponent(lblLoginWelcomeTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldEmailAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlLoginForm1Layout.createSequentialGroup()
                        .addGroup(pnlLoginForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlLoginForm1Layout.createSequentialGroup()
                                .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnSignUp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(pwdFieldForLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lblLoginBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlLoginForm1Layout.setVerticalGroup(
            pnlLoginForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginForm1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblLoginWelcomeTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubTitleForLoginInstructions1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFieldEmailAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlLoginForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginForm1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pwdFieldForLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginForm1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnShow)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLoginForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignUp1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblLoginBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlLoginFrame1Layout = new javax.swing.GroupLayout(pnlLoginFrame1);
        pnlLoginFrame1.setLayout(pnlLoginFrame1Layout);
        pnlLoginFrame1Layout.setHorizontalGroup(
            pnlLoginFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginFrame1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(pnlLoginForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        pnlLoginFrame1Layout.setVerticalGroup(
            pnlLoginFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginFrame1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(pnlLoginForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        getContentPane().add(pnlLoginFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pwdFieldForLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdFieldForLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdFieldForLoginActionPerformed
    int flag=0;
    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        
        if(flag==0){
            pwdFieldForLogin.setEchoChar((char)0);
            btnShow.setText("Hide");
            flag=1;
        }
        else{
            pwdFieldForLogin.setEchoChar('*');
            btnShow.setText("Show");
            flag=0;
        }
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        // TODO add your handling code here:
        if(txtFieldEmailAddress1.getText().equals("admin@gmail.com")&&pwdFieldForLogin.getText().equals("admin"))
        {
            this.dispose();
            new HomePage().setVisible(true);
        } 
        else{
            
            lblErrorMessage.setText("Incorrect username or password. Try again..");
        }
    }//GEN-LAST:event_btnLogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnSignUp1;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblLoginBackground;
    private javax.swing.JLabel lblLoginWelcomeTitle1;
    private javax.swing.JLabel lblSubTitleForLoginInstructions1;
    private javax.swing.JPanel pnlLoginForm1;
    private javax.swing.JPanel pnlLoginFrame1;
    private javax.swing.JPasswordField pwdFieldForLogin;
    private javax.swing.JTextField txtFieldEmailAddress1;
    // End of variables declaration//GEN-END:variables
}
